In [24]:
import pandas as pd
import numpy as np
from scipy import spatial

In [25]:
clean_filepath = "/Users/kylieleblancKylie/domino/docsim/data/clean/"

In [26]:
docs = pd.read_csv(clean_filepath + 'corpus_text_noavatars.csv')
docs = docs.set_index('doc')
docs.sample(5)

,text,year,semester
doc,,,
105-2C.docx,Alrighty. So how do you think that went? You...,2017-18,spring
2019_66_5C_Transcript.docx,"All right, so how do you think that went? ...",2018-19,spring
2019_119_5C_Transcript.docx,"Alright. So, how are you feeling about ...",2018-19,spring
2019_34_5C_Transcript.docx,"So, how are you feeling about that first sim...",2018-19,spring
96-2C.docx,Okay I'm glad you made it. Um- so how do...,2017-18,spring

In [27]:
matrix = pd.read_csv(clean_filepath + 'doc_term_matrix_corpus_noavatars.csv')
matrix = matrix.set_index('doc')
matrix.sample(5)

,10,100,12,15,16,20,29,30,40,7th,...,york,you,young,younger,your,yours,yourself,yup,zen,zone
doc,,,,,,,,,,,,,,,,,,,,,
104-2C.docx,0,0,0,0,0,0,0,0,0,0,...,0,43,0,0,5,0,0,0,0,0
109-2C.docx,0,0,0,0,0,0,0,0,0,0,...,0,68,0,0,6,0,0,0,0,0
64-2C.docx,0,0,0,0,0,0,0,1,1,0,...,0,60,0,0,2,0,1,0,0,0
2019_97_5C_Transcript.docx,0,0,0,0,0,0,0,0,0,0,...,0,53,0,0,3,0,1,0,0,0
2019_107_5C_Transcript.docx,0,0,0,0,0,0,0,0,0,0,...,0,46,0,0,2,0,0,0,0,0

In [28]:
ideal_matrix = pd.read_csv(clean_filepath + 'doc_term_matrix_ideal_noavatars.csv')
ideal_matrix = ideal_matrix.set_index('doc')
ideal_matrix.sample()

,10,100,12,15,16,20,29,30,40,7th,...,york,you,young,younger,your,yours,yourself,yup,zen,zone
doc,,,,,,,,,,,,,,,,,,,,,
Classroom Management Model D.docx,0,0,0,0,0,0,0,0,0,0,...,0,21,0,0,4,0,1,0,0,0

In [29]:
centroid = np.mean(ideal_matrix)
centroid

10          0.00
100         0.00
12          0.00
15          0.00
16          0.00
            ...
yours       0.00
yourself    0.25
yup         0.00
zen         0.00
zone        0.00
Length: 2649, dtype: float64

In [34]:
def distance_to_ideal(df, semester, year):
    for maindoc in list(docs[(docs.year == year) & (docs.semester == semester)].index):
        pairwise_sim = []
        sim = 1 - spatial.distance.cosine(matrix.loc[maindoc], centroid)
        pairwise_sim.append(sim)
        average = sum(pairwise_sim)/len(pairwise_sim) # don't include relationship with self
        docs.at[maindoc, 'to_ideal'] = average
    return df
distance_to_ideal(docs, 'spring', '2018-19')
docs.sample(5)

,text,year,semester,to_ideal
doc,,,,
103-2C.docx,All right. Why don't you have a sit and we'l...,2017-18,spring,0.615012
2018_41_3C Transcript .docx,"So, how do you feel about that first one? ...",2018-19,fall,NaN
2018_93_3C_Transcript.docx,Awesome. How do you feel about how it went...,2018-19,fall,NaN
72-2C.docx,So how do you feel about that? Yeah? Ava...,2017-18,spring,0.629932
2019_61_5C_Transcript.docx,Go ahead and tell me your thoughts about wha...,2018-19,spring,0.827037

In [33]:
docs.loc['110-2C.docx'].text

'  So how do you feel? how did you get -   It went okay?   Okay and so, hopefully  five minutes to talk about some skills, some things that you can do to make you feel like-- You know, "it\'s the best five minutes ever."   Um, so I think you did a really nice job, one thing that I was really happy to see is that you provided really specific feedback and I mean, you know, I kept hearing you say, you know, we\'re still being silent um,  no drumming, so it\'s very specific in behaviors . And so it\'s really important that interactions are specifics so the students know exactly what you want them to do.   Um, so one thing I think that we can do in the next simulation um, is try to work to make your re-directions a little more succinct,um, because sometimes they just took a little but-   -longer-   -Than what I think they could. So let\'s say um- let think about Avatar talking about Classic Man.   Yeah. So um,  what do you think is uh, one way that you could like make the uh, re-directions succinct?   Oh, okay .   Oh.   Okay.   Yeah. So I- yeah I think like being very like succinct and then being like let\'s relate this to classroom-   -more, so like very clearly, like naming the action and then where you  h-happen.   And so lets\'s think of another example, uh, so the first time like you- we started and Avatar\'s making those voices-   -or something like that. Uh, so what is a way that you could respond that is specific and succinct to um, Avatar making noise?   Yeah, I think you can do that, you seem very hesitant with that, like-   No, I think that, you know, they\'re tons of different ways you can do succinct. You know you can do, "Avatar please be quiet," you know, succinct doesn\'t   -you know and that\'s one way that\'s just- you can get right back to it, things like that.   So, why do you think it\'s like a good idea to use these like succinct-   Yeah, yeah and I think because it like- it can also can just like change the whole attitude of the classroom too, and you\'re just like spending so long talking about these things that you don\'t- and I think you even said at the end about classrooms, I haven\'t heard from Savannah and Avatar yet just because it takes so much time.   So I think providing those specific succinct-   -   Okay. Do we-- how long do we have?   Great, so let\'s do, would you do a bit of role playing? I will be an off task student um, and you can practice different ways to um, make me .   Yes.   I should have a little fun  all right. So-   Yeah.   So it\'s addressing it right away, it\'s being very specific-   - um, and succinct  right back into  you know, so they can  expectations.   So, just saying it over a really nice, calm voice-   -which he didn\'t seem to get very riled   in the last one. So, just take that approach and-   -you know, "Please, be quiet,"and more .   Okay. Do you have any questions or-   Okay.   Right. You wanna try another way? Or you- Okay, all right. Um, good, so we\'re going to focus on specific, succinct, "be quiet", voices off, "listen silently-"   -those things.   Okay?   All right.'